/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import drivers.NewTestDriver;
import interfaces.GoBackButton;
import javax.swing.JButton;
import javax.swing.JFrame;
import utils.GuiUtils;

/**
 *
 * @author David Vazquez
 */
public class NewTest extends javax.swing.JFrame implements GoBackButton {

    private static NewTest INSTANCE = new NewTest();

    public static NewTest getInstance() {
        return INSTANCE;
    }

    /**
     * Creates new form NewTest
     */
    private NewTest() {
        initComponents();
        GuiUtils.initJFrame(this);
        new NewTestDriver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        itemCount = new javax.swing.JLabel();
        startTest = new javax.swing.JButton();
        goBack = new javax.swing.JButton();
        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo examen");

        jLabel5.setText("Seleccione número de reactivos:");

        jLabel1.setText("Total de reactivos seleccionados:");

        itemCount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        itemCount.setText("999,999");

        startTest.setText("Iniciar test");
        startTest.setEnabled(false);

        goBack.setText("Regresar");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(goBack))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemCount, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 384, Short.MAX_VALUE)
                        .addComponent(startTest)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(goBack))
                .addGap(18, 18, 18)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(itemCount)
                    .addComponent(startTest))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        com.alee.laf.WebLookAndFeel.install();
        new NewTest().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goBack;
    private javax.swing.JLabel itemCount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panel;
    private javax.swing.JButton startTest;
    // End of variables declaration//GEN-END:variables

    @Override
    public JButton getGoBackButton() {
        return goBack;
    }

    @Override
    public void setGoBackButton(JButton newGoBackButton) {
        goBack = newGoBackButton;
    }

    public javax.swing.JButton getStartTest() {
        return startTest;
    }

    public void setStartTest(javax.swing.JButton startTest) {
        this.startTest = startTest;
    }

    public javax.swing.JButton getGoBack() {
        return goBack;
    }

    public void setGoBack(javax.swing.JButton goBack) {
        this.goBack = goBack;
    }

    public javax.swing.JLabel getItemCount() {
        return itemCount;
    }

    public void setItemCount(javax.swing.JLabel itemCount) {
        this.itemCount = itemCount;
    }

    public javax.swing.JPanel getPanel() {
        return panel;
    }

    public void setPanel(javax.swing.JPanel panel) {
        this.panel = panel;
    }
}
